# Generated by Django 6.0.6 on 2026-06-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='propertylayer',
            name='unique_property_geoserver_layer',
        ),
        migrations.DeleteModel(
            name='PropertyLayer',
        ),
    ]
