# Generated by Django 6.0.6 on 2026-06-10 10:04

import Core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_remove_propertylayer_unique_property_geoserver_layer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property3dmodel',
            name='file',
            field=models.FileField(upload_to=Core.models.property_asset_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb', 'gltf', 'obj', 'dem'])]),
        ),
    ]
