# Generated by Django 6.0.6 on 2026-06-10 10:38

import Core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_property3dmodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to=Core.models.property_cover_upload_path),
        ),
    ]
