# Generated by Django 6.0.6 on 2026-06-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_property_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='master_mtdc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.IntegerField(unique=True)),
                ('property_name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('pt_geom', models.TextField(blank=True, null=True)),
                ('pl_geom', models.TextField(blank=True, null=True)),
                ('poly_geom', models.TextField(blank=True, null=True)),
                ('centroid', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'master_mtdc',
                'verbose_name_plural': 'master_mtdc',
                'db_table': 'master_mtdc',
                'managed': False,
            },
        ),
    ]
