# Generated by Django 6.0.6 on 2026-06-23 15:24

import Core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_master_mtdc'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.IntegerField(unique=True)),
                ('cover_image', models.ImageField(upload_to=Core.models.property_cover_upload_path)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property Cover Photo',
                'verbose_name_plural': 'Property Cover Photos',
                'db_table': 'core_propertycover',
            },
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=Core.models.property_document_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Property Document',
                'verbose_name_plural': 'Property Documents',
                'db_table': 'core_propertydocument',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.IntegerField()),
                ('image', models.ImageField(upload_to=Core.models.property_image_upload_path)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
                'db_table': 'core_propertyimage',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
