# Generated by Django 4.2.7 on 2026-06-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_alter_propertycover_id_alter_propertydocument_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupancyJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20, unique=True)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Occupancy JSON',
                'verbose_name_plural': 'Occupancy JSONs',
                'db_table': 'core_occupancyjson',
                'ordering': ['year'],
            },
        ),
    ]
