# Generated by Django 4.2.7 on 2026-08-10 05:43

import Core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_propertymap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymap',
            name='file',
            field=models.FileField(upload_to=Core.models.property_map_upload_path, validators=[Core.models.validate_pdf]),
        ),
    ]
